import json

from typer.testing import CliRunner

from mosaicolabs_cli.main import app

runner = CliRunner()


def _invoke(tmp_path, *args):
    return runner.invoke(
        app,
        ["ai", "init", "--directory", str(tmp_path), *args],
        env={"MOSAICO_CONFIG_PATH": str(tmp_path / "mosaico-config.toml")},
    )


class TestAiInit:
    def test_both_creates_shared_and_native_guidance(self, tmp_path):
        result = _invoke(tmp_path, "--output", "json")

        assert result.exit_code == 0
        payload = json.loads(result.output)
        assert payload["schema_version"] == 1
        assert payload["assistant"] == "both"
        assert [record["path"] for record in payload["files"]] == [
            ".mosaico/AI_GUIDE.md",
            "AGENTS.md",
            "CLAUDE.md",
        ]
        assert all(record["status"] == "created" for record in payload["files"])

        guide = (tmp_path / ".mosaico" / "AI_GUIDE.md").read_text()
        assert "mosaico doctor --output json" in guide
        assert "MOSAICO_API_KEY" in guide
        assert "https://docs.mosaico.dev/llms.txt" in guide
        assert "https://docs.mosaico.dev/start.md" in guide
        assert "the source of truth" in guide
        assert "Do not invent SDK methods" in guide
        assert "spin up Mosaico" in guide
        codex_instructions = (tmp_path / "AGENTS.md").read_text()
        assert "mosaico doctor --output json" in codex_instructions
        assert "MOSAICO_API_KEY" in codex_instructions
        assert "@.mosaico/AI_GUIDE.md" in (tmp_path / "CLAUDE.md").read_text()

    def test_target_can_be_limited_to_codex(self, tmp_path):
        result = _invoke(
            tmp_path,
            "--assistant",
            "codex",
            "--output",
            "json",
        )

        assert result.exit_code == 0
        assert (tmp_path / "AGENTS.md").exists()
        assert not (tmp_path / "CLAUDE.md").exists()

    def test_existing_native_instructions_are_preserved(self, tmp_path):
        agents_path = tmp_path / "AGENTS.md"
        claude_path = tmp_path / "CLAUDE.md"
        agents_path.write_text("# Existing Codex rules\n")
        claude_path.write_text("# Existing Claude rules\n")

        result = _invoke(tmp_path, "--output", "json")

        assert result.exit_code == 0
        assert (
            (tmp_path / "AGENTS.md").read_text().startswith("# Existing Codex rules\n")
        )
        assert (
            (tmp_path / "CLAUDE.md").read_text().startswith("# Existing Claude rules\n")
        )

    def test_rerun_is_idempotent(self, tmp_path):
        first = _invoke(tmp_path, "--output", "json")
        second = _invoke(tmp_path, "--output", "json")

        assert first.exit_code == 0
        assert second.exit_code == 0
        payload = json.loads(second.output)
        assert all(record["status"] == "unchanged" for record in payload["files"])
        assert (tmp_path / "AGENTS.md").read_text().count(
            "<!-- mosaico-ai:start -->"
        ) == 1

    def test_custom_guide_requires_force_and_does_not_partially_write(self, tmp_path):
        guide_path = tmp_path / ".mosaico" / "AI_GUIDE.md"
        guide_path.parent.mkdir()
        guide_path.write_text("# Keep me\n")

        result = _invoke(tmp_path, "--output", "json")

        assert result.exit_code == 1
        assert guide_path.read_text() == "# Keep me\n"
        assert not (tmp_path / "AGENTS.md").exists()
        assert not (tmp_path / "CLAUDE.md").exists()

    def test_force_replaces_only_the_owned_guide(self, tmp_path):
        guide_path = tmp_path / ".mosaico" / "AI_GUIDE.md"
        guide_path.parent.mkdir()
        guide_path.write_text("# Replace me\n")
        agents_path = tmp_path / "AGENTS.md"
        agents_path.write_text("# Preserve me\n")

        result = _invoke(
            tmp_path,
            "--assistant",
            "codex",
            "--force",
            "--output",
            "json",
        )

        assert result.exit_code == 0
        assert guide_path.read_text().startswith("<!-- Generated by")
        assert agents_path.read_text().startswith("# Preserve me\n")

    def test_jsonl_records_are_complete_versioned_objects(self, tmp_path):
        result = _invoke(
            tmp_path,
            "--assistant",
            "claude",
            "--output",
            "jsonl",
        )

        assert result.exit_code == 0
        records = [json.loads(line) for line in result.output.splitlines()]
        assert len(records) == 2
        assert all(record["schema_version"] == 1 for record in records)
        assert {record["assistant"] for record in records} == {"shared", "claude"}

    def test_malformed_managed_block_is_not_modified(self, tmp_path):
        agents_path = tmp_path / "AGENTS.md"
        agents_path.write_text("# Existing\n<!-- mosaico-ai:start -->\n")

        result = _invoke(
            tmp_path,
            "--assistant",
            "codex",
            "--output",
            "json",
        )

        assert result.exit_code == 1
        assert agents_path.read_text() == "# Existing\n<!-- mosaico-ai:start -->\n"
        assert not (tmp_path / ".mosaico" / "AI_GUIDE.md").exists()
