from __future__ import annotations

import json
import os
import sys
import tempfile
from enum import Enum
from pathlib import Path
from typing import Optional

import typer
from rich.table import Table

from mosaicolabs_cli.utils.config import OutputFormat, console, error_console

app = typer.Typer(
    help="Prepare a project for AI-assisted Mosaico development.",
    no_args_is_help=True,
)

SCHEMA_VERSION = 1
GUIDE_PATH = Path(".mosaico/AI_GUIDE.md")
GENERATED_MARKER = (
    "<!-- Generated by `mosaico ai init`. Re-run the command to refresh. -->"
)
BLOCK_START = "<!-- mosaico-ai:start -->"
BLOCK_END = "<!-- mosaico-ai:end -->"


class AssistantTarget(str, Enum):
    CODEX = "codex"
    CLAUDE = "claude"
    BOTH = "both"


def _guide_body() -> str:
    return """# Mosaico guide for AI coding systems

Use this guide when adding Mosaico to the current project. Inspect the project and
its dependency manager before changing files. Prefer the smallest read-only
connection check before implementing ingestion or queries.

## Source of truth

- Zero-to-first-query runbook: https://docs.mosaico.dev/start.md
- Agent-navigable documentation index: https://docs.mosaico.dev/llms.txt
- Human-facing documentation: https://docs.mosaico.dev
- Python SDK package: `mosaicolabs`
- CLI package extra: `mosaicolabs[cli]`

Treat `llms.txt` and the documentation pages it links to as the source of truth
for current Mosaico behavior. Navigate to the relevant linked page before
planning an integration. Do not invent SDK methods, topic schemas, profile names,
host names, ports, or authentication requirements.

## First-run workflow

1. Identify the language, package manager, and existing Mosaico integration.
2. Check whether the CLI is available. If it is missing, propose the installation
   command that matches the project's package manager. For Python, the package is
   `mosaicolabs[cli]`.
3. Determine whether a `mosaicod` daemon is already reachable. No client call
   succeeds without one. If there is no daemon to connect to, follow
   https://docs.mosaico.dev/start.md, which contains the local development
   compose file and the startup sequence. Do not overwrite an existing
   `compose.yaml` without asking.
4. Run `mosaico doctor --output json`. Read `schema_version`, `status`, and
   `checks`; do not scrape a formatted table.
5. If no connection is configured, guide the developer through
   `mosaico profile add <name>` or the documented `MOSAICO_*` environment
   variables. Do not ask them to paste a secret into chat or source code.
6. Once diagnostics pass, use structured CLI output to inspect available data,
   starting with `mosaico sequence ls --output json`.
7. Add and run the smallest read-only SDK example. Explain the result before
   proposing writes, ingestion, schema changes, or production configuration.

## Safety and compatibility

- Never print, commit, echo, or serialize API-key values. Prefer
  `MOSAICO_API_KEY` for credentials supplied at runtime.
- Treat `--output json` and `--output jsonl` as versioned interfaces. Inspect
  `schema_version` and keep stdout machine-readable.
- Confirm identifiers and ontology or topic schemas before writing data.
- Preserve the project's error handling, lifecycle, and dependency conventions.
- State which diagnostics, tests, and end-to-end behavior were actually run.

## Starter request

Treat "spin up Mosaico", "set up Mosaico", or "connect this project to Mosaico"
as a request to run the first-run workflow above, in order, as:

> Inspect the existing stack, start or locate a `mosaicod` daemon, run
> machine-readable diagnostics, and implement the smallest read-only connection
> example. Do not expose credentials or guess schemas. Explain each proposed
> change and verify the result.
"""


def _guide_content() -> str:
    return f"{GENERATED_MARKER}\n{_guide_body()}"


def _codex_block() -> str:
    return f"""{BLOCK_START}
{_guide_body().rstrip()}
{BLOCK_END}"""


def _claude_block() -> str:
    return f"""{BLOCK_START}
## Mosaico integration

@{GUIDE_PATH.as_posix()}
{BLOCK_END}"""


def _merge_managed_block(existing: str, block: str, path: Path) -> str:
    start = existing.find(BLOCK_START)
    end = existing.find(BLOCK_END)
    if (start == -1) != (end == -1) or (start != -1 and end < start):
        raise ValueError(
            f"{path} has an incomplete Mosaico managed block; repair the markers before retrying."
        )

    if start != -1:
        end += len(BLOCK_END)
        return f"{existing[:start]}{block}{existing[end:]}"

    if not existing.strip():
        return f"{block}\n"
    return f"{existing.rstrip()}\n\n{block}\n"


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path: Optional[Path] = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=path.parent,
            prefix=f".{path.name}.",
            delete=False,
        ) as temporary_file:
            temporary_file.write(content)
            temporary_path = Path(temporary_file.name)

        if os.name == "posix":
            temporary_path.chmod(0o644)
        temporary_path.replace(path)
    finally:
        if temporary_path is not None and temporary_path.exists():
            temporary_path.unlink()


def _plan_file(path: Path, content: str) -> tuple[str, str]:
    if not path.exists():
        return "created", content
    existing = path.read_text(encoding="utf-8")
    return ("unchanged" if existing == content else "updated"), content


def _render_table(records: list[dict[str, str]], target: AssistantTarget) -> None:
    table = Table(
        title=f"Mosaico AI setup: {target.value}",
        header_style="bold cyan",
        box=None,
    )
    table.add_column("File", style="bold white")
    table.add_column("For")
    table.add_column("Status")
    for record in records:
        table.add_row(record["path"], record["assistant"], record["status"])
    console.print(table)
    console.print()
    console.print("Start your AI coding tool in this directory and ask:")
    console.print(
        '  "Connect this project to Mosaico using the generated first-run guide."'
    )


def _emit_output(
    records: list[dict[str, str]],
    target: AssistantTarget,
    directory: Path,
    output: OutputFormat,
) -> None:
    if output == OutputFormat.TABLE:
        _render_table(records, target)
        return

    if output == OutputFormat.CSV:
        print("schema_version,assistant,path,status")
        for record in records:
            print(
                f"{SCHEMA_VERSION},{record['assistant']},"
                f"{json.dumps(record['path'])},{record['status']}"
            )
        return

    if output == OutputFormat.JSONL:
        for record in records:
            print(
                json.dumps({"schema_version": SCHEMA_VERSION, **record}, sort_keys=True)
            )
        return

    print(
        json.dumps(
            {
                "schema_version": SCHEMA_VERSION,
                "assistant": target.value,
                "directory": str(directory),
                "files": records,
            },
            sort_keys=True,
        )
    )


@app.command(name="init")
def init_ai(
    directory: Path = typer.Option(
        Path("."),
        "--directory",
        "-d",
        exists=True,
        file_okay=False,
        dir_okay=True,
        resolve_path=True,
        help="Project directory to prepare.",
    ),
    assistant: AssistantTarget = typer.Option(
        AssistantTarget.BOTH,
        "--assistant",
        help="AI coding system to prepare.",
        case_sensitive=False,
    ),
    force: bool = typer.Option(
        False,
        "--force",
        help="Replace an existing non-generated .mosaico/AI_GUIDE.md file.",
    ),
    output: Optional[OutputFormat] = typer.Option(
        None,
        "--output",
        "-o",
        help="Output setup results as table, CSV, JSON, or JSON Lines.",
    ),
) -> None:
    """Generate safe, project-local Mosaico guidance for Codex and Claude."""
    directory = directory.resolve()
    guide_path = directory / GUIDE_PATH
    guide = _guide_content()

    if guide_path.exists():
        existing_guide = guide_path.read_text(encoding="utf-8")
        is_generated = existing_guide.startswith(GENERATED_MARKER)
        if existing_guide != guide and not is_generated and not force:
            error_console.print(
                f"Error: {guide_path} already exists and was not generated by Mosaico. "
                "Re-run with --force to replace it."
            )
            raise typer.Exit(code=1)

    planned: list[tuple[Path, str, str]] = []
    _, guide_content = _plan_file(guide_path, guide)
    planned.append((guide_path, "shared", guide_content))

    native_files: list[tuple[Path, str, str]] = []
    if assistant in (AssistantTarget.CODEX, AssistantTarget.BOTH):
        native_files.append((directory / "AGENTS.md", "codex", _codex_block()))
    if assistant in (AssistantTarget.CLAUDE, AssistantTarget.BOTH):
        native_files.append((directory / "CLAUDE.md", "claude", _claude_block()))

    try:
        for path, owner, block in native_files:
            existing = path.read_text(encoding="utf-8") if path.exists() else ""
            merged = _merge_managed_block(existing, block, path)
            planned.append((path, owner, merged))
    except (OSError, UnicodeError, ValueError) as exc:
        error_console.print(f"Error: {exc}")
        raise typer.Exit(code=1)

    records: list[dict[str, str]] = []
    for path, owner, content in planned:
        status, _ = _plan_file(path, content)
        if status != "unchanged":
            _atomic_write(path, content)
        records.append(
            {
                "assistant": owner,
                "path": path.relative_to(directory).as_posix(),
                "status": status,
            }
        )

    selected_output = output or (
        OutputFormat.TABLE if sys.stdout.isatty() else OutputFormat.JSON
    )
    _emit_output(records, assistant, directory, selected_output)
